language: python
python:
- 3.5.2
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: gS8nMeypLFHSe9Nyh617jcvhCJM8seu5ZWDVRlYy2XVlp9WAK3f0suTyVhGHJlZVMMWmZP91hqGhb/niVnJ1TdYfea5Nu2Ct2wlET75m+Hds0bl57nLIi+UHSHW9sHskniST8M527GEfvbhnZAdJG3TokLsGnCs68BbHgL7k9Q9VSz0ubOJuV6MHjjVORsWGwHUEcQxBBXKcS95dR1/uMvgnAHXq4z6Hwh3hnIcZxVQ80JkU8H4+KQlPS/hqQfvkkfffzsw/TWQ+9pCxmqKh94JCRLK6JxE13vrdZOJ2ONT9uI9Bguv/kl/GbYceqm256WLHgPfgIPB/Eo6oQiGLk0ZD1oFmzm4yeAMi7sdjAYeEr08Wodb/GhN6esQXWNHVzZWeZG0Z9scIh12SpDempoRHBaUF9IlZQwd1xL1Xj8vyrM/A7CsP5h7PWWL8o4nafJi8ous0BpWbwjpD/P25KSwVtftczJ3bX2dmKT9tY+W1PVii0bUsftzl853WduCV+SeV94x7szP3aPB6eREBAUVaPb8aR8NwKVTUHXt8208IPAa90F+MNBDvW4vkItiXM/aUvYLjnGg8AfnzmRHwT+c4VA5rC9wJVdapUbyib3iglDlfofbbljloO3Y9YlYXciSHPiHimeKc6GHeLWluEXDxrBaolyZwVF1gEQqY2b4=
  app: pythonexperiments
  on:
    repo: dfyepez/PythonExperiments
